GET http://localhost:4000/image/detail?id=02666e37-4458-4fbe-a55f-77077029d901

###
GET http://localhost:4000/image/chat?prompt=你是谁

###
POST http://localhost:4000/image/text2image
Content-Type: application/json

{
  "prompt":"童话世界"
}